language: objective-c
osx_image: xcode9.0
script:
  - pod lib lint
  - set -o pipefail
  - xcodebuild test -scheme EggsBenedict -destination "name=iPhone 6s Plus" -sdk iphonesimulator | xcpretty -c
notifications:
  email: false
